[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "superfluid-contracts/=lib/superfluid-protocol-monorepo/packages/ethereum-contracts/contracts",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
