[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "superfluid-contracts/=lib/superfluid-protocol-monorepo/packages/ethereum-contracts/contracts",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
    "@uniswap/swap-router-contracts/contracts/=lib/swap-router-contracts/contracts/",
    "@prb/math/=lib/prb-math/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
